AVG_PRICE_PER_SQM = 25  # CHF per m² per month baseline
FURNISHED_PREMIUM = 200  # expected CHF markup for furnished flats

HSG_COORDS = {"lat": 47.4305, "lon": 9.3755}
BAHNHOF_COORDS = {"lat": 47.4233, "lon": 9.3695}

NEIGHBORHOODS = {
    "Rosenberg": {
        "location_score": 9,
        "student_score": 6,
        "transit_score": 7,
        "avg_rent": 1400,
        "vibe": "Gehoben, nahe HSG",
        "lat": 47.4330,
        "lon": 9.3720,
    },
    "Rotmonten": {
        "location_score": 8,
        "student_score": 6,
        "transit_score": 6,
        "avg_rent": 1300,
        "vibe": "Ruhig, nahe HSG",
        "lat": 47.4380,
        "lon": 9.3850,
    },
    "St. Georgen": {
        "location_score": 7,
        "student_score": 8,
        "transit_score": 7,
        "avg_rent": 1100,
        "vibe": "Hügelig, studierendenfreundlich",
        "lat": 47.4190,
        "lon": 9.3580,
    },
    "Zentrum / Altstadt": {
        "location_score": 7,
        "student_score": 9,
        "transit_score": 10,
        "avg_rent": 1350,
        "vibe": "Zentral, lebhaft",
        "lat": 47.4245,
        "lon": 9.3770,
    },
    "Riethüsli": {
        "location_score": 7,
        "student_score": 5,
        "transit_score": 5,
        "avg_rent": 1150,
        "vibe": "Ruhig, campusnah",
        "lat": 47.4350,
        "lon": 9.3920,
    },
    "Tablat": {
        "location_score": 6,
        "student_score": 4,
        "transit_score": 7,
        "avg_rent": 1100,
        "vibe": "Wohngebiet, gute ÖV-Anbindung",
        "lat": 47.4400,
        "lon": 9.3950,
    },
    "Lachen": {
        "location_score": 6,
        "student_score": 7,
        "transit_score": 8,
        "avg_rent": 1050,
        "vibe": "Durchmischt, günstig",
        "lat": 47.4200,
        "lon": 9.3850,
    },
    "Vonwil": {
        "location_score": 6,
        "student_score": 9,
        "transit_score": 6,
        "avg_rent": 1050,
        "vibe": "Studierendenwohngebiet",
        "lat": 47.4280,
        "lon": 9.3650,
    },
    "Heiligkreuz": {
        "location_score": 5,
        "student_score": 4,
        "transit_score": 6,
        "avg_rent": 1000,
        "vibe": "Gemischtes Wohngebiet",
        "lat": 47.4150,
        "lon": 9.3750,
    },
    "Neudorf": {
        "location_score": 5,
        "student_score": 4,
        "transit_score": 6,
        "avg_rent": 1000,
        "vibe": "Wohngebiet",
        "lat": 47.4270,
        "lon": 9.3950,
    },
    "Schoren": {
        "location_score": 5,
        "student_score": 3,
        "transit_score": 4,
        "avg_rent": 950,
        "vibe": "Wohngebiet, ruhiger",
        "lat": 47.4150,
        "lon": 9.3550,
    },
    "Haggen": {
        "location_score": 4,
        "student_score": 3,
        "transit_score": 5,
        "avg_rent": 950,
        "vibe": "Wohngebiet, weiter draussen",
        "lat": 47.4350,
        "lon": 9.3500,
    },
    "Wittenbach": {
        "location_score": 4,
        "student_score": 2,
        "transit_score": 4,
        "avg_rent": 900,
        "vibe": "Ausserhalb der Stadt, günstiger",
        "lat": 47.4580,
        "lon": 9.3850,
    },
    "Winkeln": {
        "location_score": 3,
        "student_score": 2,
        "transit_score": 5,
        "avg_rent": 850,
        "vibe": "Abgelegen, Industriegebiet",
        "lat": 47.4100,
        "lon": 9.3300,
    },
    "Bruggen": {
        "location_score": 3,
        "student_score": 3,
        "transit_score": 4,
        "avg_rent": 900,
        "vibe": "Weit im Westen",
        "lat": 47.4200,
        "lon": 9.3350,
    },
}
